# Generated by Django 5.2.7 on 2025-10-09 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('Química', 'Química'), ('Microbiología', 'Microbiología'), ('Dirección', 'Dirección'), ('Proyecto de equipamiento', 'Proyecto de equipamiento')], help_text='El departamento que hace la solicitud', max_length=50)),
                ('ref_departamento', models.CharField(blank=True, help_text='Identificación de cada departamento (M, Q, D, E)', max_length=100)),
                ('descripcion_pedido', models.TextField(help_text='Descripción general del pedido (SBS)')),
                ('monto_comprometido_sbs', models.DecimalField(decimal_places=2, help_text='Monto total de la SBS enviada a presupuesto', max_digits=10)),
                ('tipo_compra', models.CharField(choices=[('Bien', 'Bien'), ('Servicio', 'Servicio')], help_text='Si la SBS es un bien o un servicio', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Bien o Servicio',
                'verbose_name_plural': 'Solicitudes de Bienes y Servicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partida', models.CharField(blank=True, max_length=100)),
                ('condicion', models.CharField(choices=[('recorrido', 'En Recorrido'), ('ingresado_v3', 'Ingresado al V3'), ('evaluado', 'Evaluado'), ('refrendado', 'Refrendado'), ('anulado', 'Anulado'), ('finalizado', 'Finalizado')], default='recorrido', max_length=20)),
                ('fecha_ingreso_v3', models.DateField(blank=True, null=True)),
                ('sbs_numero', models.CharField(blank=True, help_text='Número de la solicitud de bienes y servicios (###-2026)', max_length=50)),
                ('fecha_pedido_evaluado', models.DateField(blank=True, null=True)),
                ('oc_numero', models.CharField(blank=True, help_text='Número de la Orden de Compra (4200#######)', max_length=100)),
                ('fecha_publicacion_oc', models.DateField(blank=True, null=True)),
                ('monto_oc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_entrega', models.CharField(blank=True, choices=[('Total', 'Total'), ('Parcial', 'Parcial')], max_length=10)),
                ('plazo_entrega', models.PositiveIntegerField(blank=True, help_text='Días para realizar la entrega', null=True)),
                ('tipo_plazo', models.CharField(blank=True, choices=[('Calendario', 'Días Calendario'), ('Habiles', 'Días Hábiles')], max_length=15)),
                ('vencimiento_oc', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=256)),
                ('solicitud_ajuste', models.TextField(blank=True)),
                ('numero_ajuste', models.CharField(blank=True, max_length=50)),
                ('nuevo_plazo_entrega', models.DateField(blank=True, null=True)),
                ('status_final_compra', models.CharField(blank=True, choices=[('Entregado', 'Entregado'), ('Realizado', 'Realizado'), ('Pendiente', 'Pendiente'), ('Por Entregar', 'Por Entregar')], max_length=20)),
                ('fecha_recibo', models.DateField(blank=True, null=True)),
                ('quien_recibe_almacen', models.CharField(blank=True, help_text='Nombre del que recibe el bien o # de Recibido Conforme', max_length=256)),
                ('observacion_1', models.TextField(blank=True)),
                ('observacion_2', models.TextField(blank=True)),
                ('mantenimiento', models.BooleanField(default=False)),
                ('calibracion', models.BooleanField(default=False)),
                ('caracterizacion', models.BooleanField(default=False)),
                ('fecha_inicial_mant_calib_caract', models.DateField(blank=True, null=True)),
                ('fecha_final_mant_calib_caract', models.DateField(blank=True, null=True)),
                ('enlace_orden_compra', models.URLField(blank=True, max_length=500)),
                ('enlace_sbs', models.URLField(blank=True, max_length=500)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Seguimiento de Compra',
                'verbose_name_plural': 'Seguimientos de Compras',
            },
        ),
    ]
